mybatis-plus:
  mapper-locations: classpath*:com/ypjiao/mettingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://8.129.211.107:3306/mooc_mettingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: ypjiao
    password: 594688
    filters: log4j,wall,mergeStat

  application:
    name: hall-service



logging:
  config: classpath:logback.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 7205


