server:
  port: 7101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hello-eureka-consumer

logging:
  config: classpath:logback.xml


feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true